### ISSUE TITLE
Faltan las etiqutas para la entrega de la evaluación estática de la documentación

### ISSUE THREAD

**Issue by miguel-latre** [albertomur96/notas-vv#1]
La entrega correspondiente a la evaluación estática de la documentación de análisis y diseño se hará principalmente a través de GitHub y, para facilitar tanto la elaboración por vuestra parte como la corrección por la nuestra, el repositorio [`miguel-latre/etiquetas-vv`](https://github.com/miguel-latre/etiquetas-vv) define un conjunto de etiquetas que deberán utilizarse en dicha entrega.

Debéis incorporarlas a vuestro repositorio `notas-vv`, ya sea creándolas manualmente, o copiándolas del repositorio `miguel-latre/etiquetas-vv` al vuestro utilizando directamente el API de GitHub o una aplicación web como [Label-Sync](https://label-sync.herokuapp.com/), cuyo código fuente se encuentra en el repositorio [`dwyl/labels`](https://github.com/dwyl/labels).

En este último caso, tened en cuenta que estaréis dando permiso de acceso a todos vuestros repositorios a esta última aplicación. En todo caso, siempre podéis revocar el acceso de Label-Sync a vuestros repositorios desde vuestro perfil de GitHub (en la sección _Applications_, pestaña _Authorized OAuth Apps_).

**Comment by albertomur96** [comment]
Deberían estar ya disponibles las etiquetas sincronizadas.

**Comment by miguel-latre** [comment]
Perfecto. Cerrad la incidencia cuando podáis.
