### ISSUE TITLE
Nuevos requisitos funcionales y no funcionales

### ISSUE THREAD

**Issue by ireneSM** [albertomur96/notas-vv#2]

**Comment by miguel-latre** [comment]
Si habéis añadido los nuevos requisitos al catálogo, podríais cerrar este _issue_.
Aunque entiendo que los habéis comentado en la memoria que habéis entregado, no estaría de más comentar en la descripción de este _issue_ cuáles son esos nuevos requisitos .

**Comment by ireneSM** [comment]
Como nuevos requisitos funcionales son:
- El usuario   podrá especificar una fecha de caducidad para la nota
- El usuario   podrá especificar una fecha de activación para la nota
- El usuario podrá modificar la fecha de activación de una nota
-El usuario podrá filtrar las notas por fecha de caducidad, activación.
Como requisitos no funcionales:
-El sistema   ofrecerá por defecto una fecha de activación de la nota, corresponderá con la  fecha actual
- El sistema   ofrecerá por defecto una fecha de caducidad de la nota, corresponderá con 30 días   después de la fecha actual
- El sistema   no permite como fecha de caducidad, anterior o igual a la fecha de activación
- Cuando se   modifica una nota, se respectará las fechas de activación y caducidad que   tuviera la nota, siempre que no se haya modificado
-Aplicación solo disponible para Android.

**Comment by miguel-latre** [comment]
Perfecto. Simplemente, recordad que el hecho de que la aplicación solo esté disponible para Android no es un requisito (ni funcional ni no funcional), sino una _restricción_.
